Algoritmo "areaquadrado"
// Disciplina  : (Linguagem e Lógica de Programação)
// Professor:   : Cintia
// Descrição   : calcular a área do quadrado
// Autor(a)    : Giovanna Alves
// Data atual  : 02/05/2020
Var
 lado, area: real
Inicio
//entrada
escreval("digite o lado do quadrado: ")
leia (lado)
//processamento
area<- lado* lado
//saída
escreval ("a área de quadrado é:", area)

Fimalgoritmo