Algoritmo "somaquadradro"
// Descrição   : dizer o quadrado e a soma de quatro numeros
// Autor(a)    : Giovanna Alves
// Data atual  : 15/05/2020
Var
a,b,c,d,t:real
Inicio
//entrada
escreval("digite um numero")
leia(a)
escreval("digite mais um numero")
leia(b)
escreval("digite mais um numero")
leia(c)
escreval("digite mais um numero")
leia(d)
//procesamento
t<-(a*a)+(b*b)+(c*c)+(d*d)
//saida
escreval("o quadrado com a soma desses numeros é:",t)
Fimalgoritmo