Algoritmo "ENQUANTO"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Giovanna
// Data atual  : 01/09/2020
Var
x, total, qntd:inteiro
Inicio
ESCREVAL("*****************************")
escreval("ENQUANTO")
ESCREVAL("*****************************")
x<-1
enquanto (x<=10)faca
escreval("digite um numero")
leia(x)
//acumulador
total<-total+x
//contador
qntd<-qntd+1
fimenquanto
escreval(total)

Fimalgoritmo