Algoritmo "parouimpar"
// Disciplina   : [Linguagem e L?gica de Programa??o]
// Professor   : Antonio Carlos Nicolodi
// Descri??o   : Aqui voc? descreve o que o programa faz! (fun??o)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/07/2020
Var
n,p:real


Inicio
escreval("digite um numero que eu direi se ele ? par ou impar:")
leia(n)

p <- (n mod 2)
escolha p

caso 1
escreval("seu numero ? impar")

caso 0
escreval("seu numero ? par")
fimescolha

Fimalgoritmo
