Algoritmo "imparPar"
// Lógica de Programação e Algoritmo
// Professora Cíntia Pinho
// Descrição   : Fazer o programa que mostra se um numero é impar ou par
// Autor(a)    :
// Data atual  : 21/06/2020
Var
// Seção de Declarações das variáveis
numeroX:real

Inicio
// Entrada

escreval("Escreva um numero qualquer")
leia(numeroX)

se (numeroX mod 2) = 0 entao

escreval("PAR")
senao

escreval("ÏMPAR")
fimse

Fimalgoritmo