Algoritmo "ex7"
// Descrição   : pedir ao usuario varios numeros inteiros, o programa devera
//ler e somar numeros ate que o valor digitado seja zero ( 0 )
// Autor(a)    : Giovanna
// Data atual  : 01/09/2020
Var
num, resul: inteiro
Inicio
num <- 1
enquanto (num <> 0)faca
escreval("Digite um numero")
leia(num)
resul<- resul + num
fimenquanto
escreval("A soma dos numeros é: ",resul)

Fimalgoritmo